<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use DB;

class StudentDetailsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('studentDetails')->insert([
            [
                'image_path' => 'img/studentImages/BIT2021EN001.png',
                'batch' => 2021,
                'enrolment_no' => 'BIT2021EN001',
                'date_of_admission' => '2021-08-15',
                'register_no' => 'REG2021A001',
                'student_name' => 'John Doe',
                'dte_reg_no' => 'DTE2021A001',
                'gender' => 'Male',
                'application_no' => 12345,
                'date_of_birth' => '2000-07-15',
                'admission_no' => 10001,
                'age' => 21,
                'father_name' => 'Michael Doe',
                'community' => 'General',
                'mother_name' => 'Jane Doe',
                'guardian_name' => 'Michael Doe',
                'religion' => 'Christianity',
                'nationality' => 'Indian',
                'occupation' => 'Engineer',
                'mother_tongue' => 'English',
                'place_of_work' => 'Chennai',
                'blood_group' => 'B+',
                'designation' => 'Senior Engineer',
                'student_id' => 20001,
                'parent_income' => 500000.00,
                'aadhar_no' => '123412341234',

                // Academic Details
                'branch_code' => 'CS',
                'year' => 3,
                'degree_level' => 'UG',
                'semester' => '5',
                'course_code' => 'CS101',
                'year_of_admission' => 2021,
                'course_name' => 'Computer Science',
                'year_of_completion' => 2024,
                'branch_name' => 'CSE',
                'section' => 'A',
                'department' => 'Computer Science',
                'student_category' => 'Regular',
                'branch_type' => 'Full-Time',
                'seat_category' => 'Merit',
                'regulation' => 2021,
                'quota' => 'Management',
                'university' => 'BIT',
                'student_status' => 'Active',

                // Admission Payment Details
                'dte_register_no' => 123456,
                'dte_payment_receipt_no' => 'PAY123',
                'dte_admission_no' => 'ADM123',
                'dte_receipt_date' => '2021-08-20',
                'dte_general_rank' => 10,
                'dte_receipt_amount' => 75000.00,
                'dte_community_rank' => 5,
                'dte_name_of_the_bank_dd' => 'ICICI',
                'entrance_marks_min' => '90',
                'admission_discount_name1' => 'Merit Discount',
                'entrance_marks_max' => '100',
                'admission_discount_amount' => 5000.00,
                'entrance_register_no' => 'ENT2021A001',
                'admission_discount_name2' => 'None',
                'admission_discount_amount2' => 0.00,

                // Insurance Details
                'nominee_name' => 'Michael Doe',
                'nominee_relationship' => 'Father',
                'nominee_age' => 50,

                // Address for Communication
                'permanent_address' => '123, Main Street, Chennai',
                'present_address' => '123, Main Street, Chennai',
                'parent_mobile_no' => '9876543210',
                'location_of_the_residence' => 'Chennai',
                'student_mobile_no' => '9876543211',
                'student_email_id' => 'johndoe@example.com',
                'official_email_id' => 'john.doe@bit.edu',
                'parent_email_id' => 'michaeldoe@example.com',
                'general_notes1' => 'N/A',
                'general_notes2' => 'N/A',
                'general_notes3' => 'N/A',
                'general_notes4' => 'N/A',

                // Class Advisor / Hostel Details
                'hosteller_or_dayscholar' => 'Dayscholar',
                'hostel_room_capacity' => 0,
                'hostel_name' => null,
                'hostel_floor_no' => null,
                'hostel_room_type' => null,
                'hostel_room_no' => null,
                'warden_name' => null,
                'warden_alter' => null,
                'h_discontinued_date' => null,
                'h_note' => null,
                'class_advisor' => 'Prof. Jane',

                // School Certificate Details
                'school_reg_no1' => 'SCH123A',
                'school_certificate_no1' => 'CERT123A',
                'school_total_marks1' => 475.50,
                'school_reg_no2' => 'SCH124A',
                'school_certificate_no2' => 'CERT124A',
                'school_total_marks2' => 485.50,
                'school_reg_no3' => 'SCH125A',
                'school_certificate_no3' => 'CERT125A',
                'school_total_marks3' => 495.00,
                'school_reg_no4' => 'SCH126A',
                'school_certificate_no4' => 'CERT126A',
                'school_total_marks4' => 500.00,

                // School TC Details
                'school_name' => 'ABC Higher Secondary School',
                'school_tc_name' => 'TCA123',
                'school_tc_no' => 1001,
                'school_tc_date' => '2021-08-01',
                'cut_off' => 95.00,
                'school_tc_class' => '12th Grade',
                'marks_note1' => 'Excellent',
                'board_of_school' => 'State Board',
                'marks_note2' => 'N/A',

                // BIT Academic Details
                'tc_last_class_date' => '2021-07-30',
                'final_total_marks_min' => 480.00,
                'tc_promotion' => 'Yes',
                'final_total_marks_max' => 500.00,
                'tc_reason_for_leaving' => 'Completed',
                'final_total_marks' => 495.00,
                'tc_conduct_and_character' => 'Excellent',
                'final_classification' => 4.9,
                'tc_no' => 'TC2021A123',
                'final_year_of_pass' => 2024,
                'tc_date' => '2021-08-01',
                'university_rank' => 1,
                'duplicate_tc_issued' => 'No',
                'university_rank1' => 1,
                'duplicate_tc_description' => null,

                // Additional Information
                'scopus_link' => 'N/A',
                'google_scholor_link' => 'N/A',
                'gmail_h_index' => 'N/A',
                'scopus_h_index_safe' => 'N/A',
                'scopus_id' => 'N/A',
                'scopus_hindex_from_scopus' => 'N/A',
                'research_gate_profile_link' => 'N/A',
                'orcid_profile_link' => 'N/A',
                '14_point_score' => 'N/A',

                // Remaining fields...
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'image_path' => 'img/studentImages/BIT2021EN002.png',
                'batch' => 2021,
                'enrolment_no' => 'BIT2021EN002',
                'date_of_admission' => '2021-08-16',
                'register_no' => 'REG2021A002',
                'student_name' => 'Alice Johnson',
                'dte_reg_no' => 'DTE2021A002',
                'gender' => 'Female',
                'application_no' => 12346,
                'date_of_birth' => '2001-03-22',
                'admission_no' => 10002,
                'age' => 20,
                'father_name' => 'Peter Johnson',
                'community' => 'OBC',
                'mother_name' => 'Anna Johnson',
                'guardian_name' => 'Peter Johnson',
                'religion' => 'Hinduism',
                'nationality' => 'Indian',
                'occupation' => 'Teacher',
                'mother_tongue' => 'Tamil',
                'place_of_work' => 'Coimbatore',
                'blood_group' => 'O+',
                'designation' => 'Lecturer',
                'student_id' => 20002,
                'parent_income' => 600000.00,
                'aadhar_no' => '223412341234',

                // Academic Details
                'branch_code' => 'CS',
                'year' => 3,
                'degree_level' => 'UG',
                'semester' => '5',
                'course_code' => 'CS101',
                'year_of_admission' => 2021,
                'course_name' => 'Computer Science',
                'year_of_completion' => 2024,
                'branch_name' => 'CSE',
                'section' => 'A',
                'department' => 'Computer Science',
                'student_category' => 'Regular',
                'branch_type' => 'Full-Time',
                'seat_category' => 'Merit',
                'regulation' => 2021,
                'quota' => 'Management',
                'university' => 'BIT',
                'student_status' => 'Active',

                // Admission Payment Details
                'dte_register_no' => 123456,
                'dte_payment_receipt_no' => 'PAY123',
                'dte_admission_no' => 'ADM123',
                'dte_receipt_date' => '2021-08-20',
                'dte_general_rank' => 10,
                'dte_receipt_amount' => 75000.00,
                'dte_community_rank' => 5,
                'dte_name_of_the_bank_dd' => 'ICICI',
                'entrance_marks_min' => '90',
                'admission_discount_name1' => 'Merit Discount',
                'entrance_marks_max' => '100',
                'admission_discount_amount' => 5000.00,
                'entrance_register_no' => 'ENT2021A001',
                'admission_discount_name2' => 'None',
                'admission_discount_amount2' => 0.00,

                // Insurance Details
                'nominee_name' => 'Michael Doe',
                'nominee_relationship' => 'Father',
                'nominee_age' => 50,

                // Address for Communication
                'permanent_address' => '123, Main Street, Chennai',
                'present_address' => '123, Main Street, Chennai',
                'parent_mobile_no' => '9876543210',
                'location_of_the_residence' => 'Chennai',
                'student_mobile_no' => '9876543211',
                'student_email_id' => 'johndoe@example.com',
                'official_email_id' => 'john.doe@bit.edu',
                'parent_email_id' => 'michaeldoe@example.com',
                'general_notes1' => 'N/A',
                'general_notes2' => 'N/A',
                'general_notes3' => 'N/A',
                'general_notes4' => 'N/A',

                // Class Advisor / Hostel Details
                'hosteller_or_dayscholar' => 'Dayscholar',
                'hostel_room_capacity' => 0,
                'hostel_name' => null,
                'hostel_floor_no' => null,
                'hostel_room_type' => null,
                'hostel_room_no' => null,
                'warden_name' => null,
                'warden_alter' => null,
                'h_discontinued_date' => null,
                'h_note' => null,
                'class_advisor' => 'Prof. Jane',

                // School Certificate Details
                'school_reg_no1' => 'SCH123A',
                'school_certificate_no1' => 'CERT123A',
                'school_total_marks1' => 475.50,
                'school_reg_no2' => 'SCH124A',
                'school_certificate_no2' => 'CERT124A',
                'school_total_marks2' => 485.50,
                'school_reg_no3' => 'SCH125A',
                'school_certificate_no3' => 'CERT125A',
                'school_total_marks3' => 495.00,
                'school_reg_no4' => 'SCH126A',
                'school_certificate_no4' => 'CERT126A',
                'school_total_marks4' => 500.00,

                // School TC Details
                'school_name' => 'ABC Higher Secondary School',
                'school_tc_name' => 'TCA123',
                'school_tc_no' => 1001,
                'school_tc_date' => '2021-08-01',
                'cut_off' => 95.00,
                'school_tc_class' => '12th Grade',
                'marks_note1' => 'Excellent',
                'board_of_school' => 'State Board',
                'marks_note2' => 'N/A',

                // BIT Academic Details
                'tc_last_class_date' => '2021-07-30',
                'final_total_marks_min' => 480.00,
                'tc_promotion' => 'Yes',
                'final_total_marks_max' => 500.00,
                'tc_reason_for_leaving' => 'Completed',
                'final_total_marks' => 495.00,
                'tc_conduct_and_character' => 'Excellent',
                'final_classification' => 4.9,
                'tc_no' => 'TC2021A123',
                'final_year_of_pass' => 2024,
                'tc_date' => '2021-08-01',
                'university_rank' => 1,
                'duplicate_tc_issued' => 'No',
                'university_rank1' => 1,
                'duplicate_tc_description' => null,

                // Additional Information
                'scopus_link' => 'N/A',
                'google_scholor_link' => 'N/A',
                'gmail_h_index' => 'N/A',
                'scopus_h_index_safe' => 'N/A',
                'scopus_id' => 'N/A',
                'scopus_hindex_from_scopus' => 'N/A',
                'research_gate_profile_link' => 'N/A',
                'orcid_profile_link' => 'N/A',
                '14_point_score' => 'N/A',

                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'image_path' => 'img/studentImages/BIT2021EN003.png',
                'batch' => 2021,
                'enrolment_no' => 'BIT2021EN003',
                'date_of_admission' => '2021-08-17',
                'register_no' => 'REG2021A003',
                'student_name' => 'Robert Brown',
                'dte_reg_no' => 'DTE2021A003',
                'gender' => 'Male',
                'application_no' => 12347,
                'date_of_birth' => '1999-10-10',
                'admission_no' => 10003,
                'age' => 22,
                'father_name' => 'George Brown',
                'community' => 'SC',
                'mother_name' => 'Mary Brown',
                'guardian_name' => 'George Brown',
                'religion' => 'Christianity',
                'nationality' => 'Indian',
                'occupation' => 'Doctor',
                'mother_tongue' => 'English',
                'place_of_work' => 'Delhi',
                'blood_group' => 'A+',
                'designation' => 'Cardiologist',
                'student_id' => 20003,
                'parent_income' => 800000.00,
                'aadhar_no' => '323412341234',

                // Academic Details
                'branch_code' => 'CS',
                'year' => 3,
                'degree_level' => 'UG',
                'semester' => '5',
                'course_code' => 'CS101',
                'year_of_admission' => 2021,
                'course_name' => 'Computer Science',
                'year_of_completion' => 2024,
                'branch_name' => 'CSE',
                'section' => 'A',
                'department' => 'Computer Science',
                'student_category' => 'Regular',
                'branch_type' => 'Full-Time',
                'seat_category' => 'Merit',
                'regulation' => 2021,
                'quota' => 'Management',
                'university' => 'BIT',
                'student_status' => 'Active',

                // Admission Payment Details
                'dte_register_no' => 123456,
                'dte_payment_receipt_no' => 'PAY123',
                'dte_admission_no' => 'ADM123',
                'dte_receipt_date' => '2021-08-20',
                'dte_general_rank' => 10,
                'dte_receipt_amount' => 75000.00,
                'dte_community_rank' => 5,
                'dte_name_of_the_bank_dd' => 'ICICI',
                'entrance_marks_min' => '90',
                'admission_discount_name1' => 'Merit Discount',
                'entrance_marks_max' => '100',
                'admission_discount_amount' => 5000.00,
                'entrance_register_no' => 'ENT2021A001',
                'admission_discount_name2' => 'None',
                'admission_discount_amount2' => 0.00,

                // Insurance Details
                'nominee_name' => 'Michael Doe',
                'nominee_relationship' => 'Father',
                'nominee_age' => 50,

                // Address for Communication
                'permanent_address' => '123, Main Street, Chennai',
                'present_address' => '123, Main Street, Chennai',
                'parent_mobile_no' => '9876543210',
                'location_of_the_residence' => 'Chennai',
                'student_mobile_no' => '9876543211',
                'student_email_id' => 'johndoe@example.com',
                'official_email_id' => 'john.doe@bit.edu',
                'parent_email_id' => 'michaeldoe@example.com',
                'general_notes1' => 'N/A',
                'general_notes2' => 'N/A',
                'general_notes3' => 'N/A',
                'general_notes4' => 'N/A',

                // Class Advisor / Hostel Details
                'hosteller_or_dayscholar' => 'Dayscholar',
                'hostel_room_capacity' => 0,
                'hostel_name' => null,
                'hostel_floor_no' => null,
                'hostel_room_type' => null,
                'hostel_room_no' => null,
                'warden_name' => null,
                'warden_alter' => null,
                'h_discontinued_date' => null,
                'h_note' => null,
                'class_advisor' => 'Prof. Jane',

                // School Certificate Details
                'school_reg_no1' => 'SCH123A',
                'school_certificate_no1' => 'CERT123A',
                'school_total_marks1' => 475.50,
                'school_reg_no2' => 'SCH124A',
                'school_certificate_no2' => 'CERT124A',
                'school_total_marks2' => 485.50,
                'school_reg_no3' => 'SCH125A',
                'school_certificate_no3' => 'CERT125A',
                'school_total_marks3' => 495.00,
                'school_reg_no4' => 'SCH126A',
                'school_certificate_no4' => 'CERT126A',
                'school_total_marks4' => 500.00,

                // School TC Details
                'school_name' => 'ABC Higher Secondary School',
                'school_tc_name' => 'TCA123',
                'school_tc_no' => 1001,
                'school_tc_date' => '2021-08-01',
                'cut_off' => 95.00,
                'school_tc_class' => '12th Grade',
                'marks_note1' => 'Excellent',
                'board_of_school' => 'State Board',
                'marks_note2' => 'N/A',

                // BIT Academic Details
                'tc_last_class_date' => '2021-07-30',
                'final_total_marks_min' => 480.00,
                'tc_promotion' => 'Yes',
                'final_total_marks_max' => 500.00,
                'tc_reason_for_leaving' => 'Completed',
                'final_total_marks' => 495.00,
                'tc_conduct_and_character' => 'Excellent',
                'final_classification' => 4.9,
                'tc_no' => 'TC2021A123',
                'final_year_of_pass' => 2024,
                'tc_date' => '2021-08-01',
                'university_rank' => 1,
                'duplicate_tc_issued' => 'No',
                'university_rank1' => 1,
                'duplicate_tc_description' => null,

                // Additional Information
                'scopus_link' => 'N/A',
                'google_scholor_link' => 'N/A',
                'gmail_h_index' => 'N/A',
                'scopus_h_index_safe' => 'N/A',
                'scopus_id' => 'N/A',
                'scopus_hindex_from_scopus' => 'N/A',
                'research_gate_profile_link' => 'N/A',
                'orcid_profile_link' => 'N/A',
                '14_point_score' => 'N/A',

                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'image_path' => 'img/studentImages/BIT2021EN004.png',
                'batch' => 2021,
                'enrolment_no' => 'BIT2021EN004',
                'date_of_admission' => '2021-08-18',
                'register_no' => 'REG2021A004',
                'student_name' => 'Emma Davis',
                'dte_reg_no' => 'DTE2021A004',
                'gender' => 'Female',
                'application_no' => 12348,
                'date_of_birth' => '2001-02-05',
                'admission_no' => 10004,
                'age' => 20,
                'father_name' => 'Henry Davis',
                'community' => 'General',
                'mother_name' => 'Lucy Davis',
                'guardian_name' => 'Henry Davis',
                'religion' => 'Islam',
                'nationality' => 'Indian',
                'occupation' => 'Engineer',
                'mother_tongue' => 'Urdu',
                'place_of_work' => 'Mumbai',
                'blood_group' => 'AB+',
                'designation' => 'Software Engineer',
                'student_id' => 20004,
                'parent_income' => 450000.00,
                'aadhar_no' => '423412341234',

                // Academic Details
                'branch_code' => 'CS',
                'year' => 3,
                'degree_level' => 'UG',
                'semester' => '5',
                'course_code' => 'CS101',
                'year_of_admission' => 2021,
                'course_name' => 'Computer Science',
                'year_of_completion' => 2024,
                'branch_name' => 'CSE',
                'section' => 'A',
                'department' => 'Computer Science',
                'student_category' => 'Regular',
                'branch_type' => 'Full-Time',
                'seat_category' => 'Merit',
                'regulation' => 2021,
                'quota' => 'Management',
                'university' => 'BIT',
                'student_status' => 'Active',

                // Admission Payment Details
                'dte_register_no' => 123456,
                'dte_payment_receipt_no' => 'PAY123',
                'dte_admission_no' => 'ADM123',
                'dte_receipt_date' => '2021-08-20',
                'dte_general_rank' => 10,
                'dte_receipt_amount' => 75000.00,
                'dte_community_rank' => 5,
                'dte_name_of_the_bank_dd' => 'ICICI',
                'entrance_marks_min' => '90',
                'admission_discount_name1' => 'Merit Discount',
                'entrance_marks_max' => '100',
                'admission_discount_amount' => 5000.00,
                'entrance_register_no' => 'ENT2021A001',
                'admission_discount_name2' => 'None',
                'admission_discount_amount2' => 0.00,

                // Insurance Details
                'nominee_name' => 'Michael Doe',
                'nominee_relationship' => 'Father',
                'nominee_age' => 50,

                // Address for Communication
                'permanent_address' => '123, Main Street, Chennai',
                'present_address' => '123, Main Street, Chennai',
                'parent_mobile_no' => '9876543210',
                'location_of_the_residence' => 'Chennai',
                'student_mobile_no' => '9876543211',
                'student_email_id' => 'johndoe@example.com',
                'official_email_id' => 'john.doe@bit.edu',
                'parent_email_id' => 'michaeldoe@example.com',
                'general_notes1' => 'N/A',
                'general_notes2' => 'N/A',
                'general_notes3' => 'N/A',
                'general_notes4' => 'N/A',

                // Class Advisor / Hostel Details
                'hosteller_or_dayscholar' => 'Dayscholar',
                'hostel_room_capacity' => 0,
                'hostel_name' => null,
                'hostel_floor_no' => null,
                'hostel_room_type' => null,
                'hostel_room_no' => null,
                'warden_name' => null,
                'warden_alter' => null,
                'h_discontinued_date' => null,
                'h_note' => null,
                'class_advisor' => 'Prof. Jane',

                // School Certificate Details
                'school_reg_no1' => 'SCH123A',
                'school_certificate_no1' => 'CERT123A',
                'school_total_marks1' => 475.50,
                'school_reg_no2' => 'SCH124A',
                'school_certificate_no2' => 'CERT124A',
                'school_total_marks2' => 485.50,
                'school_reg_no3' => 'SCH125A',
                'school_certificate_no3' => 'CERT125A',
                'school_total_marks3' => 495.00,
                'school_reg_no4' => 'SCH126A',
                'school_certificate_no4' => 'CERT126A',
                'school_total_marks4' => 500.00,

                // School TC Details
                'school_name' => 'ABC Higher Secondary School',
                'school_tc_name' => 'TCA123',
                'school_tc_no' => 1001,
                'school_tc_date' => '2021-08-01',
                'cut_off' => 95.00,
                'school_tc_class' => '12th Grade',
                'marks_note1' => 'Excellent',
                'board_of_school' => 'State Board',
                'marks_note2' => 'N/A',

                // BIT Academic Details
                'tc_last_class_date' => '2021-07-30',
                'final_total_marks_min' => 480.00,
                'tc_promotion' => 'Yes',
                'final_total_marks_max' => 500.00,
                'tc_reason_for_leaving' => 'Completed',
                'final_total_marks' => 495.00,
                'tc_conduct_and_character' => 'Excellent',
                'final_classification' => 4.9,
                'tc_no' => 'TC2021A123',
                'final_year_of_pass' => 2024,
                'tc_date' => '2021-08-01',
                'university_rank' => 1,
                'duplicate_tc_issued' => 'No',
                'university_rank1' => 1,
                'duplicate_tc_description' => null,

                // Additional Information
                'scopus_link' => 'N/A',
                'google_scholor_link' => 'N/A',
                'gmail_h_index' => 'N/A',
                'scopus_h_index_safe' => 'N/A',
                'scopus_id' => 'N/A',
                'scopus_hindex_from_scopus' => 'N/A',
                'research_gate_profile_link' => 'N/A',
                'orcid_profile_link' => 'N/A',
                '14_point_score' => 'N/A',

                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'image_path' => 'img/studentImages/BIT2021EN005.png',
                'batch' => 2021,
                'enrolment_no' => 'BIT2021EN005',
                'date_of_admission' => '2021-08-19',
                'register_no' => 'REG2021A005',
                'student_name' => 'Sophia Martinez',
                'dte_reg_no' => 'DTE2021A005',
                'gender' => 'Female',
                'application_no' => 12349,
                'date_of_birth' => '2000-12-15',
                'admission_no' => 10005,
                'age' => 21,
                'father_name' => 'Carlos Martinez',
                'community' => 'OBC',
                'mother_name' => 'Maria Martinez',
                'guardian_name' => 'Carlos Martinez',
                'religion' => 'Christianity',
                'nationality' => 'Indian',
                'occupation' => 'Banker',
                'mother_tongue' => 'Spanish',
                'place_of_work' => 'Bangalore',
                'blood_group' => 'O-',
                'designation' => 'Manager',
                'student_id' => 20005,
                'parent_income' => 700000.00,
                'aadhar_no' => '523412341234',

                // Academic Details
                'branch_code' => 'CS',
                'year' => 3,
                'degree_level' => 'UG',
                'semester' => '5',
                'course_code' => 'CS101',
                'year_of_admission' => 2021,
                'course_name' => 'Computer Science',
                'year_of_completion' => 2024,
                'branch_name' => 'CSE',
                'section' => 'A',
                'department' => 'Computer Science',
                'student_category' => 'Regular',
                'branch_type' => 'Full-Time',
                'seat_category' => 'Merit',
                'regulation' => 2021,
                'quota' => 'Management',
                'university' => 'BIT',
                'student_status' => 'Active',

                // Admission Payment Details
                'dte_register_no' => 123456,
                'dte_payment_receipt_no' => 'PAY123',
                'dte_admission_no' => 'ADM123',
                'dte_receipt_date' => '2021-08-20',
                'dte_general_rank' => 10,
                'dte_receipt_amount' => 75000.00,
                'dte_community_rank' => 5,
                'dte_name_of_the_bank_dd' => 'ICICI',
                'entrance_marks_min' => '90',
                'admission_discount_name1' => 'Merit Discount',
                'entrance_marks_max' => '100',
                'admission_discount_amount' => 5000.00,
                'entrance_register_no' => 'ENT2021A001',
                'admission_discount_name2' => 'None',
                'admission_discount_amount2' => 0.00,

                // Insurance Details
                'nominee_name' => 'Michael Doe',
                'nominee_relationship' => 'Father',
                'nominee_age' => 50,

                // Address for Communication
                'permanent_address' => '123, Main Street, Chennai',
                'present_address' => '123, Main Street, Chennai',
                'parent_mobile_no' => '9876543210',
                'location_of_the_residence' => 'Chennai',
                'student_mobile_no' => '9876543211',
                'student_email_id' => 'johndoe@example.com',
                'official_email_id' => 'john.doe@bit.edu',
                'parent_email_id' => 'michaeldoe@example.com',
                'general_notes1' => 'N/A',
                'general_notes2' => 'N/A',
                'general_notes3' => 'N/A',
                'general_notes4' => 'N/A',

                // Class Advisor / Hostel Details
                'hosteller_or_dayscholar' => 'Dayscholar',
                'hostel_room_capacity' => 0,
                'hostel_name' => null,
                'hostel_floor_no' => null,
                'hostel_room_type' => null,
                'hostel_room_no' => null,
                'warden_name' => null,
                'warden_alter' => null,
                'h_discontinued_date' => null,
                'h_note' => null,
                'class_advisor' => 'Prof. Jane',

                // School Certificate Details
                'school_reg_no1' => 'SCH123A',
                'school_certificate_no1' => 'CERT123A',
                'school_total_marks1' => 475.50,
                'school_reg_no2' => 'SCH124A',
                'school_certificate_no2' => 'CERT124A',
                'school_total_marks2' => 485.50,
                'school_reg_no3' => 'SCH125A',
                'school_certificate_no3' => 'CERT125A',
                'school_total_marks3' => 495.00,
                'school_reg_no4' => 'SCH126A',
                'school_certificate_no4' => 'CERT126A',
                'school_total_marks4' => 500.00,

                // School TC Details
                'school_name' => 'ABC Higher Secondary School',
                'school_tc_name' => 'TCA123',
                'school_tc_no' => 1001,
                'school_tc_date' => '2021-08-01',
                'cut_off' => 95.00,
                'school_tc_class' => '12th Grade',
                'marks_note1' => 'Excellent',
                'board_of_school' => 'State Board',
                'marks_note2' => 'N/A',

                // BIT Academic Details
                'tc_last_class_date' => '2021-07-30',
                'final_total_marks_min' => 480.00,
                'tc_promotion' => 'Yes',
                'final_total_marks_max' => 500.00,
                'tc_reason_for_leaving' => 'Completed',
                'final_total_marks' => 495.00,
                'tc_conduct_and_character' => 'Excellent',
                'final_classification' => 4.9,
                'tc_no' => 'TC2021A123',
                'final_year_of_pass' => 2024,
                'tc_date' => '2021-08-01',
                'university_rank' => 1,
                'duplicate_tc_issued' => 'No',
                'university_rank1' => 1,
                'duplicate_tc_description' => null,

                // Additional Information
                'scopus_link' => 'N/A',
                'google_scholor_link' => 'N/A',
                'gmail_h_index' => 'N/A',
                'scopus_h_index_safe' => 'N/A',
                'scopus_id' => 'N/A',
                'scopus_hindex_from_scopus' => 'N/A',
                'research_gate_profile_link' => 'N/A',
                'orcid_profile_link' => 'N/A',
                '14_point_score' => 'N/A',

                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'image_path' => 'img/studentImages/BIT2021EN006.png',
                'batch' => 2021,
                'enrolment_no' => 'BIT2021EN006',
                'date_of_admission' => '2021-08-20',
                'register_no' => 'REG2021A006',
                'student_name' => 'Liam Wilson',
                'dte_reg_no' => 'DTE2021A006',
                'gender' => 'Male',
                'application_no' => 12350,
                'date_of_birth' => '1999-11-25',
                'admission_no' => 10006,
                'age' => 22,
                'father_name' => 'David Wilson',
                'community' => 'General',
                'mother_name' => 'Sara Wilson',
                'guardian_name' => 'David Wilson',
                'religion' => 'Hinduism',
                'nationality' => 'Indian',
                'occupation' => 'Farmer',
                'mother_tongue' => 'Hindi',
                'place_of_work' => 'Pune',
                'blood_group' => 'B-',
                'designation' => 'Agriculturist',
                'student_id' => 20006,
                'parent_income' => 350000.00,
                'aadhar_no' => '623412341234',

                // Academic Details
                'branch_code' => 'CS',
                'year' => 3,
                'degree_level' => 'UG',
                'semester' => '5',
                'course_code' => 'CS101',
                'year_of_admission' => 2021,
                'course_name' => 'Computer Science',
                'year_of_completion' => 2024,
                'branch_name' => 'CSE',
                'section' => 'A',
                'department' => 'Computer Science',
                'student_category' => 'Regular',
                'branch_type' => 'Full-Time',
                'seat_category' => 'Merit',
                'regulation' => 2021,
                'quota' => 'Management',
                'university' => 'BIT',
                'student_status' => 'Active',

                // Admission Payment Details
                'dte_register_no' => 123456,
                'dte_payment_receipt_no' => 'PAY123',
                'dte_admission_no' => 'ADM123',
                'dte_receipt_date' => '2021-08-20',
                'dte_general_rank' => 10,
                'dte_receipt_amount' => 75000.00,
                'dte_community_rank' => 5,
                'dte_name_of_the_bank_dd' => 'ICICI',
                'entrance_marks_min' => '90',
                'admission_discount_name1' => 'Merit Discount',
                'entrance_marks_max' => '100',
                'admission_discount_amount' => 5000.00,
                'entrance_register_no' => 'ENT2021A001',
                'admission_discount_name2' => 'None',
                'admission_discount_amount2' => 0.00,

                // Insurance Details
                'nominee_name' => 'Michael Doe',
                'nominee_relationship' => 'Father',
                'nominee_age' => 50,

                // Address for Communication
                'permanent_address' => '123, Main Street, Chennai',
                'present_address' => '123, Main Street, Chennai',
                'parent_mobile_no' => '9876543210',
                'location_of_the_residence' => 'Chennai',
                'student_mobile_no' => '9876543211',
                'student_email_id' => 'johndoe@example.com',
                'official_email_id' => 'john.doe@bit.edu',
                'parent_email_id' => 'michaeldoe@example.com',
                'general_notes1' => 'N/A',
                'general_notes2' => 'N/A',
                'general_notes3' => 'N/A',
                'general_notes4' => 'N/A',

                // Class Advisor / Hostel Details
                'hosteller_or_dayscholar' => 'Dayscholar',
                'hostel_room_capacity' => 0,
                'hostel_name' => null,
                'hostel_floor_no' => null,
                'hostel_room_type' => null,
                'hostel_room_no' => null,
                'warden_name' => null,
                'warden_alter' => null,
                'h_discontinued_date' => null,
                'h_note' => null,
                'class_advisor' => 'Prof. Jane',

                // School Certificate Details
                'school_reg_no1' => 'SCH123A',
                'school_certificate_no1' => 'CERT123A',
                'school_total_marks1' => 475.50,
                'school_reg_no2' => 'SCH124A',
                'school_certificate_no2' => 'CERT124A',
                'school_total_marks2' => 485.50,
                'school_reg_no3' => 'SCH125A',
                'school_certificate_no3' => 'CERT125A',
                'school_total_marks3' => 495.00,
                'school_reg_no4' => 'SCH126A',
                'school_certificate_no4' => 'CERT126A',
                'school_total_marks4' => 500.00,

                // School TC Details
                'school_name' => 'ABC Higher Secondary School',
                'school_tc_name' => 'TCA123',
                'school_tc_no' => 1001,
                'school_tc_date' => '2021-08-01',
                'cut_off' => 95.00,
                'school_tc_class' => '12th Grade',
                'marks_note1' => 'Excellent',
                'board_of_school' => 'State Board',
                'marks_note2' => 'N/A',

                // BIT Academic Details
                'tc_last_class_date' => '2021-07-30',
                'final_total_marks_min' => 480.00,
                'tc_promotion' => 'Yes',
                'final_total_marks_max' => 500.00,
                'tc_reason_for_leaving' => 'Completed',
                'final_total_marks' => 495.00,
                'tc_conduct_and_character' => 'Excellent',
                'final_classification' => 4.9,
                'tc_no' => 'TC2021A123',
                'final_year_of_pass' => 2024,
                'tc_date' => '2021-08-01',
                'university_rank' => 1,
                'duplicate_tc_issued' => 'No',
                'university_rank1' => 1,
                'duplicate_tc_description' => null,

                // Additional Information
                'scopus_link' => 'N/A',
                'google_scholor_link' => 'N/A',
                'gmail_h_index' => 'N/A',
                'scopus_h_index_safe' => 'N/A',
                'scopus_id' => 'N/A',
                'scopus_hindex_from_scopus' => 'N/A',
                'research_gate_profile_link' => 'N/A',
                'orcid_profile_link' => 'N/A',
                '14_point_score' => 'N/A',

                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'image_path' => 'img/studentImages/BIT2021EN007.png',
                'batch' => 2021,
                'enrolment_no' => 'BIT2021EN007',
                'date_of_admission' => '2021-08-21',
                'register_no' => 'REG2021A007',
                'student_name' => 'Noah Garcia',
                'dte_reg_no' => 'DTE2021A007',
                'gender' => 'Male',
                'application_no' => 12351,
                'date_of_birth' => '2000-01-10',
                'admission_no' => 10007,
                'age' => 21,
                'father_name' => 'John Garcia',
                'community' => 'General',
                'mother_name' => 'Eva Garcia',
                'guardian_name' => 'John Garcia',
                'religion' => 'Christianity',
                'nationality' => 'Indian',
                'occupation' => 'Artist',
                'mother_tongue' => 'English',
                'place_of_work' => 'Hyderabad',
                'blood_group' => 'A-',
                'designation' => 'Painter',
                'student_id' => 20007,
                'parent_income' => 400000.00,
                'aadhar_no' => '723412341234',

                // Academic Details
                'branch_code' => 'CS',
                'year' => 3,
                'degree_level' => 'UG',
                'semester' => '5',
                'course_code' => 'CS101',
                'year_of_admission' => 2021,
                'course_name' => 'Computer Science',
                'year_of_completion' => 2024,
                'branch_name' => 'CSE',
                'section' => 'A',
                'department' => 'Computer Science',
                'student_category' => 'Regular',
                'branch_type' => 'Full-Time',
                'seat_category' => 'Merit',
                'regulation' => 2021,
                'quota' => 'Management',
                'university' => 'BIT',
                'student_status' => 'Active',

                // Admission Payment Details
                'dte_register_no' => 123456,
                'dte_payment_receipt_no' => 'PAY123',
                'dte_admission_no' => 'ADM123',
                'dte_receipt_date' => '2021-08-20',
                'dte_general_rank' => 10,
                'dte_receipt_amount' => 75000.00,
                'dte_community_rank' => 5,
                'dte_name_of_the_bank_dd' => 'ICICI',
                'entrance_marks_min' => '90',
                'admission_discount_name1' => 'Merit Discount',
                'entrance_marks_max' => '100',
                'admission_discount_amount' => 5000.00,
                'entrance_register_no' => 'ENT2021A001',
                'admission_discount_name2' => 'None',
                'admission_discount_amount2' => 0.00,

                // Insurance Details
                'nominee_name' => 'Michael Doe',
                'nominee_relationship' => 'Father',
                'nominee_age' => 50,

                // Address for Communication
                'permanent_address' => '123, Main Street, Chennai',
                'present_address' => '123, Main Street, Chennai',
                'parent_mobile_no' => '9876543210',
                'location_of_the_residence' => 'Chennai',
                'student_mobile_no' => '9876543211',
                'student_email_id' => 'johndoe@example.com',
                'official_email_id' => 'john.doe@bit.edu',
                'parent_email_id' => 'michaeldoe@example.com',
                'general_notes1' => 'N/A',
                'general_notes2' => 'N/A',
                'general_notes3' => 'N/A',
                'general_notes4' => 'N/A',

                // Class Advisor / Hostel Details
                'hosteller_or_dayscholar' => 'Dayscholar',
                'hostel_room_capacity' => 0,
                'hostel_name' => null,
                'hostel_floor_no' => null,
                'hostel_room_type' => null,
                'hostel_room_no' => null,
                'warden_name' => null,
                'warden_alter' => null,
                'h_discontinued_date' => null,
                'h_note' => null,
                'class_advisor' => 'Prof. Jane',

                // School Certificate Details
                'school_reg_no1' => 'SCH123A',
                'school_certificate_no1' => 'CERT123A',
                'school_total_marks1' => 475.50,
                'school_reg_no2' => 'SCH124A',
                'school_certificate_no2' => 'CERT124A',
                'school_total_marks2' => 485.50,
                'school_reg_no3' => 'SCH125A',
                'school_certificate_no3' => 'CERT125A',
                'school_total_marks3' => 495.00,
                'school_reg_no4' => 'SCH126A',
                'school_certificate_no4' => 'CERT126A',
                'school_total_marks4' => 500.00,

                // School TC Details
                'school_name' => 'ABC Higher Secondary School',
                'school_tc_name' => 'TCA123',
                'school_tc_no' => 1001,
                'school_tc_date' => '2021-08-01',
                'cut_off' => 95.00,
                'school_tc_class' => '12th Grade',
                'marks_note1' => 'Excellent',
                'board_of_school' => 'State Board',
                'marks_note2' => 'N/A',

                // BIT Academic Details
                'tc_last_class_date' => '2021-07-30',
                'final_total_marks_min' => 480.00,
                'tc_promotion' => 'Yes',
                'final_total_marks_max' => 500.00,
                'tc_reason_for_leaving' => 'Completed',
                'final_total_marks' => 495.00,
                'tc_conduct_and_character' => 'Excellent',
                'final_classification' => 4.9,
                'tc_no' => 'TC2021A123',
                'final_year_of_pass' => 2024,
                'tc_date' => '2021-08-01',
                'university_rank' => 1,
                'duplicate_tc_issued' => 'No',
                'university_rank1' => 1,
                'duplicate_tc_description' => null,

                // Additional Information
                'scopus_link' => 'N/A',
                'google_scholor_link' => 'N/A',
                'gmail_h_index' => 'N/A',
                'scopus_h_index_safe' => 'N/A',
                'scopus_id' => 'N/A',
                'scopus_hindex_from_scopus' => 'N/A',
                'research_gate_profile_link' => 'N/A',
                'orcid_profile_link' => 'N/A',
                '14_point_score' => 'N/A',

                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'image_path' => 'img/studentImages/BIT2021EN008.png',
                'batch' => 2021,
                'enrolment_no' => 'BIT2021EN008',
                'date_of_admission' => '2021-08-22',
                'register_no' => 'REG2021A008',
                'student_name' => 'William Taylor',
                'dte_reg_no' => 'DTE2021A008',
                'gender' => 'Male',
                'application_no' => 12352,
                'date_of_birth' => '2001-05-10',
                'admission_no' => 10008,
                'age' => 20,
                'father_name' => 'James Taylor',
                'community' => 'SC',
                'mother_name' => 'Emily Taylor',
                'guardian_name' => 'James Taylor',
                'religion' => 'Hinduism',
                'nationality' => 'Indian',
                'occupation' => 'Businessman',
                'mother_tongue' => 'English',
                'place_of_work' => 'Chennai',
                'blood_group' => 'O+',
                'designation' => 'CEO',
                'student_id' => 20008,
                'parent_income' => 1000000.00,
                'aadhar_no' => '823412341234',

                // Academic Details
                'branch_code' => 'CS',
                'year' => 3,
                'degree_level' => 'UG',
                'semester' => '5',
                'course_code' => 'CS101',
                'year_of_admission' => 2021,
                'course_name' => 'Computer Science',
                'year_of_completion' => 2024,
                'branch_name' => 'CSE',
                'section' => 'A',
                'department' => 'Computer Science',
                'student_category' => 'Regular',
                'branch_type' => 'Full-Time',
                'seat_category' => 'Merit',
                'regulation' => 2021,
                'quota' => 'Management',
                'university' => 'BIT',
                'student_status' => 'Active',

                // Admission Payment Details
                'dte_register_no' => 123456,
                'dte_payment_receipt_no' => 'PAY123',
                'dte_admission_no' => 'ADM123',
                'dte_receipt_date' => '2021-08-20',
                'dte_general_rank' => 10,
                'dte_receipt_amount' => 75000.00,
                'dte_community_rank' => 5,
                'dte_name_of_the_bank_dd' => 'ICICI',
                'entrance_marks_min' => '90',
                'admission_discount_name1' => 'Merit Discount',
                'entrance_marks_max' => '100',
                'admission_discount_amount' => 5000.00,
                'entrance_register_no' => 'ENT2021A001',
                'admission_discount_name2' => 'None',
                'admission_discount_amount2' => 0.00,

                // Insurance Details
                'nominee_name' => 'Michael Doe',
                'nominee_relationship' => 'Father',
                'nominee_age' => 50,

                // Address for Communication
                'permanent_address' => '123, Main Street, Chennai',
                'present_address' => '123, Main Street, Chennai',
                'parent_mobile_no' => '9876543210',
                'location_of_the_residence' => 'Chennai',
                'student_mobile_no' => '9876543211',
                'student_email_id' => 'johndoe@example.com',
                'official_email_id' => 'john.doe@bit.edu',
                'parent_email_id' => 'michaeldoe@example.com',
                'general_notes1' => 'N/A',
                'general_notes2' => 'N/A',
                'general_notes3' => 'N/A',
                'general_notes4' => 'N/A',

                // Class Advisor / Hostel Details
                'hosteller_or_dayscholar' => 'Dayscholar',
                'hostel_room_capacity' => 0,
                'hostel_name' => null,
                'hostel_floor_no' => null,
                'hostel_room_type' => null,
                'hostel_room_no' => null,
                'warden_name' => null,
                'warden_alter' => null,
                'h_discontinued_date' => null,
                'h_note' => null,
                'class_advisor' => 'Prof. Jane',

                // School Certificate Details
                'school_reg_no1' => 'SCH123A',
                'school_certificate_no1' => 'CERT123A',
                'school_total_marks1' => 475.50,
                'school_reg_no2' => 'SCH124A',
                'school_certificate_no2' => 'CERT124A',
                'school_total_marks2' => 485.50,
                'school_reg_no3' => 'SCH125A',
                'school_certificate_no3' => 'CERT125A',
                'school_total_marks3' => 495.00,
                'school_reg_no4' => 'SCH126A',
                'school_certificate_no4' => 'CERT126A',
                'school_total_marks4' => 500.00,

                // School TC Details
                'school_name' => 'ABC Higher Secondary School',
                'school_tc_name' => 'TCA123',
                'school_tc_no' => 1001,
                'school_tc_date' => '2021-08-01',
                'cut_off' => 95.00,
                'school_tc_class' => '12th Grade',
                'marks_note1' => 'Excellent',
                'board_of_school' => 'State Board',
                'marks_note2' => 'N/A',

                // BIT Academic Details
                'tc_last_class_date' => '2021-07-30',
                'final_total_marks_min' => 480.00,
                'tc_promotion' => 'Yes',
                'final_total_marks_max' => 500.00,
                'tc_reason_for_leaving' => 'Completed',
                'final_total_marks' => 495.00,
                'tc_conduct_and_character' => 'Excellent',
                'final_classification' => 4.9,
                'tc_no' => 'TC2021A123',
                'final_year_of_pass' => 2024,
                'tc_date' => '2021-08-01',
                'university_rank' => 1,
                'duplicate_tc_issued' => 'No',
                'university_rank1' => 1,
                'duplicate_tc_description' => null,

                // Additional Information
                'scopus_link' => 'N/A',
                'google_scholor_link' => 'N/A',
                'gmail_h_index' => 'N/A',
                'scopus_h_index_safe' => 'N/A',
                'scopus_id' => 'N/A',
                'scopus_hindex_from_scopus' => 'N/A',
                'research_gate_profile_link' => 'N/A',
                'orcid_profile_link' => 'N/A',
                '14_point_score' => 'N/A',

                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'image_path' => 'img/studentImages/BIT2021EN009.png',
                'batch' => 2021,
                'enrolment_no' => 'BIT2021EN009',
                'date_of_admission' => '2021-08-23',
                'register_no' => 'REG2021A009',
                'student_name' => 'James Harris',
                'dte_reg_no' => 'DTE2021A009',
                'gender' => 'Male',
                'application_no' => 12353,
                'date_of_birth' => '2000-07-02',
                'admission_no' => 10009,
                'age' => 21,
                'father_name' => 'Tom Harris',
                'community' => 'General',
                'mother_name' => 'Laura Harris',
                'guardian_name' => 'Tom Harris',
                'religion' => 'Christianity',
                'nationality' => 'Indian',
                'occupation' => 'Lawyer',
                'mother_tongue' => 'Tamil',
                'place_of_work' => 'Kolkata',
                'blood_group' => 'AB-',
                'designation' => 'Legal Advisor',
                'student_id' => 20009,
                'parent_income' => 600000.00,
                'aadhar_no' => '923412341234',

                // Academic Details
                'branch_code' => 'CS',
                'year' => 3,
                'degree_level' => 'UG',
                'semester' => '5',
                'course_code' => 'CS101',
                'year_of_admission' => 2021,
                'course_name' => 'Computer Science',
                'year_of_completion' => 2024,
                'branch_name' => 'CSE',
                'section' => 'A',
                'department' => 'Computer Science',
                'student_category' => 'Regular',
                'branch_type' => 'Full-Time',
                'seat_category' => 'Merit',
                'regulation' => 2021,
                'quota' => 'Management',
                'university' => 'BIT',
                'student_status' => 'Active',

                // Admission Payment Details
                'dte_register_no' => 123456,
                'dte_payment_receipt_no' => 'PAY123',
                'dte_admission_no' => 'ADM123',
                'dte_receipt_date' => '2021-08-20',
                'dte_general_rank' => 10,
                'dte_receipt_amount' => 75000.00,
                'dte_community_rank' => 5,
                'dte_name_of_the_bank_dd' => 'ICICI',
                'entrance_marks_min' => '90',
                'admission_discount_name1' => 'Merit Discount',
                'entrance_marks_max' => '100',
                'admission_discount_amount' => 5000.00,
                'entrance_register_no' => 'ENT2021A001',
                'admission_discount_name2' => 'None',
                'admission_discount_amount2' => 0.00,

                // Insurance Details
                'nominee_name' => 'Michael Doe',
                'nominee_relationship' => 'Father',
                'nominee_age' => 50,

                // Address for Communication
                'permanent_address' => '123, Main Street, Chennai',
                'present_address' => '123, Main Street, Chennai',
                'parent_mobile_no' => '9876543210',
                'location_of_the_residence' => 'Chennai',
                'student_mobile_no' => '9876543211',
                'student_email_id' => 'hello@example.com',
                'official_email_id' => 'john.doe@bit.edu',
                'parent_email_id' => 'michaeldoe@example.com',
                'general_notes1' => 'N/A',
                'general_notes2' => 'N/A',
                'general_notes3' => 'N/A',
                'general_notes4' => 'N/A',

                // Class Advisor / Hostel Details
                'hosteller_or_dayscholar' => 'Dayscholar',
                'hostel_room_capacity' => 0,
                'hostel_name' => null,
                'hostel_floor_no' => null,
                'hostel_room_type' => null,
                'hostel_room_no' => null,
                'warden_name' => null,
                'warden_alter' => null,
                'h_discontinued_date' => null,
                'h_note' => null,
                'class_advisor' => 'Prof. Jane',

                // School Certificate Details
                'school_reg_no1' => 'SCH123A',
                'school_certificate_no1' => 'CERT123A',
                'school_total_marks1' => 475.50,
                'school_reg_no2' => 'SCH124A',
                'school_certificate_no2' => 'CERT124A',
                'school_total_marks2' => 485.50,
                'school_reg_no3' => 'SCH125A',
                'school_certificate_no3' => 'CERT125A',
                'school_total_marks3' => 495.00,
                'school_reg_no4' => 'SCH126A',
                'school_certificate_no4' => 'CERT126A',
                'school_total_marks4' => 500.00,

                // School TC Details
                'school_name' => 'ABC Higher Secondary School',
                'school_tc_name' => 'TCA123',
                'school_tc_no' => 1001,
                'school_tc_date' => '2021-08-01',
                'cut_off' => 95.00,
                'school_tc_class' => '12th Grade',
                'marks_note1' => 'Excellent',
                'board_of_school' => 'State Board',
                'marks_note2' => 'N/A',

                // BIT Academic Details
                'tc_last_class_date' => '2021-07-30',
                'final_total_marks_min' => 480.00,
                'tc_promotion' => 'Yes',
                'final_total_marks_max' => 500.00,
                'tc_reason_for_leaving' => 'Completed',
                'final_total_marks' => 495.00,
                'tc_conduct_and_character' => 'Excellent',
                'final_classification' => 4.9,
                'tc_no' => 'TC2021A123',
                'final_year_of_pass' => 2024,
                'tc_date' => '2021-08-01',
                'university_rank' => 1,
                'duplicate_tc_issued' => 'No',
                'university_rank1' => 1,
                'duplicate_tc_description' => null,

                // Additional Information
                'scopus_link' => 'N/A',
                'google_scholor_link' => 'N/A',
                'gmail_h_index' => 'N/A',
                'scopus_h_index_safe' => 'N/A',
                'scopus_id' => 'N/A',
                'scopus_hindex_from_scopus' => 'N/A',
                'research_gate_profile_link' => 'N/A',
                'orcid_profile_link' => 'N/A',
                '14_point_score' => 'N/A',

                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'image_path' => 'img/studentImages/BIT2021EN010.png',
                'batch' => 2021,
                'enrolment_no' => 'BIT2021EN010',
                'date_of_admission' => '2021-08-24',
                'register_no' => 'REG2021A010',
                'student_name' => 'Benjamin Clark',
                'dte_reg_no' => 'DTE2021A010',
                'gender' => 'Male',
                'application_no' => 12354,
                'date_of_birth' => '2001-09-20',
                'admission_no' => 10010,
                'age' => 20,
                'father_name' => 'Mark Clark',
                'community' => 'OBC',
                'mother_name' => 'Grace Clark',
                'guardian_name' => 'Mark Clark',
                'religion' => 'Islam',
                'nationality' => 'Indian',
                'occupation' => 'Professor',
                'mother_tongue' => 'Urdu',
                'place_of_work' => 'Patna',
                'blood_group' => 'A+',
                'designation' => 'Lecturer',
                'student_id' => 20010,
                'parent_income' => 550000.00,
                'aadhar_no' => '123456789012',

                // Academic Details
                'branch_code' => 'CS',
                'year' => 3,
                'degree_level' => 'UG',
                'semester' => '5',
                'course_code' => 'CS101',
                'year_of_admission' => 2021,
                'course_name' => 'Computer Science',
                'year_of_completion' => 2024,
                'branch_name' => 'CSE',
                'section' => 'A',
                'department' => 'Computer Science',
                'student_category' => 'Regular',
                'branch_type' => 'Full-Time',
                'seat_category' => 'Merit',
                'regulation' => 2021,
                'quota' => 'Management',
                'university' => 'BIT',
                'student_status' => 'Active',

                // Admission Payment Details
                'dte_register_no' => 123456,
                'dte_payment_receipt_no' => 'PAY123',
                'dte_admission_no' => 'ADM123',
                'dte_receipt_date' => '2021-08-20',
                'dte_general_rank' => 10,
                'dte_receipt_amount' => 75000.00,
                'dte_community_rank' => 5,
                'dte_name_of_the_bank_dd' => 'ICICI',
                'entrance_marks_min' => '90',
                'admission_discount_name1' => 'Merit Discount',
                'entrance_marks_max' => '100',
                'admission_discount_amount' => 5000.00,
                'entrance_register_no' => 'ENT2021A001',
                'admission_discount_name2' => 'None',
                'admission_discount_amount2' => 0.00,

                // Insurance Details
                'nominee_name' => 'Michael Doe',
                'nominee_relationship' => 'Father',
                'nominee_age' => 50,

                // Address for Communication
                'permanent_address' => '123, Main Street, Chennai',
                'present_address' => '123, Main Street, Chennai',
                'parent_mobile_no' => '9876543210',
                'location_of_the_residence' => 'Chennai',
                'student_mobile_no' => '9876543211',
                'student_email_id' => 'kavin090305@example.com',
                'official_email_id' => 'john.doe@bit.edu',
                'parent_email_id' => 'michaeldoe@example.com',
                'general_notes1' => 'N/A',
                'general_notes2' => 'N/A',
                'general_notes3' => 'N/A',
                'general_notes4' => 'N/A',

                // Class Advisor / Hostel Details
                'hosteller_or_dayscholar' => 'Dayscholar',
                'hostel_room_capacity' => 0,
                'hostel_name' => null,
                'hostel_floor_no' => null,
                'hostel_room_type' => null,
                'hostel_room_no' => null,
                'warden_name' => null,
                'warden_alter' => null,
                'h_discontinued_date' => null,
                'h_note' => null,
                'class_advisor' => 'Prof. Jane',

                // School Certificate Details
                'school_reg_no1' => 'SCH123A',
                'school_certificate_no1' => 'CERT123A',
                'school_total_marks1' => 475.50,
                'school_reg_no2' => 'SCH124A',
                'school_certificate_no2' => 'CERT124A',
                'school_total_marks2' => 485.50,
                'school_reg_no3' => 'SCH125A',
                'school_certificate_no3' => 'CERT125A',
                'school_total_marks3' => 495.00,
                'school_reg_no4' => 'SCH126A',
                'school_certificate_no4' => 'CERT126A',
                'school_total_marks4' => 500.00,

                // School TC Details
                'school_name' => 'ABC Higher Secondary School',
                'school_tc_name' => 'TCA123',
                'school_tc_no' => 1001,
                'school_tc_date' => '2021-08-01',
                'cut_off' => 95.00,
                'school_tc_class' => '12th Grade',
                'marks_note1' => 'Excellent',
                'board_of_school' => 'State Board',
                'marks_note2' => 'N/A',

                // BIT Academic Details
                'tc_last_class_date' => '2021-07-30',
                'final_total_marks_min' => 480.00,
                'tc_promotion' => 'Yes',
                'final_total_marks_max' => 500.00,
                'tc_reason_for_leaving' => 'Completed',
                'final_total_marks' => 495.00,
                'tc_conduct_and_character' => 'Excellent',
                'final_classification' => 4.9,
                'tc_no' => 'TC2021A123',
                'final_year_of_pass' => 2024,
                'tc_date' => '2021-08-01',
                'university_rank' => 1,
                'duplicate_tc_issued' => 'No',
                'university_rank1' => 1,
                'duplicate_tc_description' => null,

                // Additional Information
                'scopus_link' => 'N/A',
                'google_scholor_link' => 'N/A',
                'gmail_h_index' => 'N/A',
                'scopus_h_index_safe' => 'N/A',
                'scopus_id' => 'N/A',
                'scopus_hindex_from_scopus' => 'N/A',
                'research_gate_profile_link' => 'N/A',
                'orcid_profile_link' => 'N/A',
                '14_point_score' => 'N/A',

                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
